version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/app/flask_app
    environment:
      - FLASK_ENV=development
    command: python flask_app/app.py